openapi: 3.1.0
info:
  title: Open WebUI - Notes API
  description: API-Spezifikation für notes Router
  version: 1.0.0
paths:
  /api/v1/notes/:
    get:
      tags:
      - notes
      summary: Get Notes
      operationId: get_notes_api_v1_notes__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/NoteUserResponse'
                type: array
                title: Response Get Notes Api V1 Notes  Get
      security:
      - HTTPBearer: []
  /api/v1/notes/list:
    get:
      tags:
      - notes
      summary: Get Note List
      operationId: get_note_list_api_v1_notes_list_get
      security:
      - HTTPBearer: []
      parameters:
      - name: page
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Page
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoteTitleIdResponse'
                title: Response Get Note List Api V1 Notes List Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/notes/create:
    post:
      tags:
      - notes
      summary: Create New Note
      operationId: create_new_note_api_v1_notes_create_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteForm'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/NoteModel'
                - type: 'null'
                title: Response Create New Note Api V1 Notes Create Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/notes/{id}:
    get:
      tags:
      - notes
      summary: Get Note By Id
      operationId: get_note_by_id_api_v1_notes__id__get
      security:
      - HTTPBearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/NoteModel'
                - type: 'null'
                title: Response Get Note By Id Api V1 Notes  Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/notes/{id}/update:
    post:
      tags:
      - notes
      summary: Update Note By Id
      operationId: update_note_by_id_api_v1_notes__id__update_post
      security:
      - HTTPBearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteForm'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/NoteModel'
                - type: 'null'
                title: Response Update Note By Id Api V1 Notes  Id  Update Post
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/notes/{id}/delete:
    delete:
      tags:
      - notes
      summary: Delete Note By Id
      operationId: delete_note_by_id_api_v1_notes__id__delete_delete
      security:
      - HTTPBearer: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          title: Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: boolean
                title: Response Delete Note By Id Api V1 Notes  Id  Delete Delete
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    NoteForm:
      properties:
        title:
          type: string
          title: Title
        data:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Data
        meta:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Meta
        access_control:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Access Control
      type: object
      required:
      - title
      title: NoteForm
    NoteModel:
      properties:
        id:
          type: string
          title: Id
        user_id:
          type: string
          title: User Id
        title:
          type: string
          title: Title
        data:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Data
        meta:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Meta
        access_control:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Access Control
        created_at:
          type: integer
          title: Created At
        updated_at:
          type: integer
          title: Updated At
      type: object
      required:
      - id
      - user_id
      - title
      - created_at
      - updated_at
      title: NoteModel
    NoteTitleIdResponse:
      properties:
        id:
          type: string
          title: Id
        title:
          type: string
          title: Title
        updated_at:
          type: integer
          title: Updated At
        created_at:
          type: integer
          title: Created At
      type: object
      required:
      - id
      - title
      - updated_at
      - created_at
      title: NoteTitleIdResponse
    NoteUserResponse:
      properties:
        id:
          type: string
          title: Id
        user_id:
          type: string
          title: User Id
        title:
          type: string
          title: Title
        data:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Data
        meta:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Meta
        access_control:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Access Control
        created_at:
          type: integer
          title: Created At
        updated_at:
          type: integer
          title: Updated At
        user:
          anyOf:
          - $ref: '#/components/schemas/UserResponse'
          - type: 'null'
      type: object
      required:
      - id
      - user_id
      - title
      - created_at
      - updated_at
      title: NoteUserResponse
    UserResponse:
      properties:
        id:
          type: string
          title: Id
        name:
          type: string
          title: Name
        email:
          type: string
          title: Email
        role:
          type: string
          title: Role
        profile_image_url:
          type: string
          title: Profile Image Url
      type: object
      required:
      - id
      - name
      - email
      - role
      - profile_image_url
      title: UserResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
