openapi: 3.1.0
info:
  title: Open WebUI - Pipelines API
  description: API-Spezifikation für pipelines Router
  version: 1.0.0
paths:
  /api/v1/pipelines/list:
    get:
      tags:
      - pipelines
      summary: Get Pipelines List
      operationId: get_pipelines_list_api_v1_pipelines_list_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      security:
      - HTTPBearer: []
  /api/v1/pipelines/upload:
    post:
      tags:
      - pipelines
      summary: Upload Pipeline
      operationId: upload_pipeline_api_v1_pipelines_upload_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_pipeline_api_v1_pipelines_upload_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/pipelines/add:
    post:
      tags:
      - pipelines
      summary: Add Pipeline
      operationId: add_pipeline_api_v1_pipelines_add_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPipelineForm'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/pipelines/delete:
    delete:
      tags:
      - pipelines
      summary: Delete Pipeline
      operationId: delete_pipeline_api_v1_pipelines_delete_delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeletePipelineForm'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/pipelines/:
    get:
      tags:
      - pipelines
      summary: Get Pipelines
      operationId: get_pipelines_api_v1_pipelines__get
      security:
      - HTTPBearer: []
      parameters:
      - name: urlIdx
        in: query
        required: false
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Urlidx
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/pipelines/{pipeline_id}/valves:
    get:
      tags:
      - pipelines
      summary: Get Pipeline Valves
      operationId: get_pipeline_valves_api_v1_pipelines__pipeline_id__valves_get
      security:
      - HTTPBearer: []
      parameters:
      - name: pipeline_id
        in: path
        required: true
        schema:
          type: string
          title: Pipeline Id
      - name: urlIdx
        in: query
        required: true
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Urlidx
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/pipelines/{pipeline_id}/valves/spec:
    get:
      tags:
      - pipelines
      summary: Get Pipeline Valves Spec
      operationId: get_pipeline_valves_spec_api_v1_pipelines__pipeline_id__valves_spec_get
      security:
      - HTTPBearer: []
      parameters:
      - name: pipeline_id
        in: path
        required: true
        schema:
          type: string
          title: Pipeline Id
      - name: urlIdx
        in: query
        required: true
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Urlidx
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/pipelines/{pipeline_id}/valves/update:
    post:
      tags:
      - pipelines
      summary: Update Pipeline Valves
      operationId: update_pipeline_valves_api_v1_pipelines__pipeline_id__valves_update_post
      security:
      - HTTPBearer: []
      parameters:
      - name: pipeline_id
        in: path
        required: true
        schema:
          type: string
          title: Pipeline Id
      - name: urlIdx
        in: query
        required: true
        schema:
          anyOf:
          - type: integer
          - type: 'null'
          title: Urlidx
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
              title: Form Data
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    AddPipelineForm:
      properties:
        url:
          type: string
          title: Url
        urlIdx:
          type: integer
          title: Urlidx
      type: object
      required:
      - url
      - urlIdx
      title: AddPipelineForm
    Body_upload_pipeline_api_v1_pipelines_upload_post:
      properties:
        urlIdx:
          type: integer
          title: Urlidx
        file:
          type: string
          format: binary
          title: File
      type: object
      required:
      - urlIdx
      - file
      title: Body_upload_pipeline_api_v1_pipelines_upload_post
    DeletePipelineForm:
      properties:
        id:
          type: string
          title: Id
        urlIdx:
          type: integer
          title: Urlidx
      type: object
      required:
      - id
      - urlIdx
      title: DeletePipelineForm
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
